

--timescale 1ns/1ps


+define+TARGET_COMMON_CELLS
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR

# -F filelists/common_cells.f
#-F filelists/cva6_bender.f
#.bender/git/checkouts/axi-20e44e41874e4f1d/src/axi_sim_mem.sv

// Common Cells
-Irtl/third_party/common_cells/include

rtl/third_party/common_cells/src/cc_pkg.sv
rtl/third_party/common_cells/src/deprecated/addr_decode_dync.sv
rtl/third_party/common_cells/src/deprecated/addr_decode_napot.sv
rtl/third_party/common_cells/src/deprecated/addr_decode.sv
rtl/third_party/common_cells/src/deprecated/binary_to_gray.sv
rtl/third_party/common_cells/src/deprecated/boxcar.sv
rtl/third_party/common_cells/src/deprecated/cb_filter_pkg.sv
rtl/third_party/common_cells/src/deprecated/cb_filter.sv
rtl/third_party/common_cells/src/deprecated/cdc_2phase_clearable.sv
rtl/third_party/common_cells/src/deprecated/cdc_2phase.sv
rtl/third_party/common_cells/src/deprecated/cdc_4phase.sv
rtl/third_party/common_cells/src/deprecated/cdc_fifo_2phase.sv
rtl/third_party/common_cells/src/deprecated/cdc_fifo_gray_clearable.sv
rtl/third_party/common_cells/src/deprecated/cdc_fifo_gray.sv
rtl/third_party/common_cells/src/deprecated/cdc_reset_ctrlr_pkg.sv
rtl/third_party/common_cells/src/deprecated/cdc_reset_ctrlr.sv
rtl/third_party/common_cells/src/deprecated/cf_math_pkg.sv
rtl/third_party/common_cells/src/deprecated/clk_int_div_static.sv
rtl/third_party/common_cells/src/deprecated/clk_int_div.sv
rtl/third_party/common_cells/src/deprecated/clk_mux_glitch_free.sv
rtl/third_party/common_cells/src/deprecated/counter.sv
rtl/third_party/common_cells/src/deprecated/credit_counter.sv
rtl/third_party/common_cells/src/deprecated/delta_counter.sv
rtl/third_party/common_cells/src/deprecated/ecc_decode.sv
rtl/third_party/common_cells/src/deprecated/ecc_encode.sv
rtl/third_party/common_cells/src/deprecated/ecc_pkg.sv
rtl/third_party/common_cells/src/deprecated/edge_detect.sv
rtl/third_party/common_cells/src/deprecated/edge_propagator_ack.sv
rtl/third_party/common_cells/src/deprecated/edge_propagator_rx.sv
rtl/third_party/common_cells/src/deprecated/edge_propagator_tx.sv
rtl/third_party/common_cells/src/deprecated/edge_propagator.sv
rtl/third_party/common_cells/src/deprecated/exp_backoff.sv
rtl/third_party/common_cells/src/deprecated/fall_through_register.sv
rtl/third_party/common_cells/src/deprecated/fifo_v3.sv
rtl/third_party/common_cells/src/deprecated/gray_to_binary.sv
rtl/third_party/common_cells/src/deprecated/heaviside.sv
rtl/third_party/common_cells/src/deprecated/id_queue.sv
rtl/third_party/common_cells/src/deprecated/isochronous_4phase_handshake.sv
rtl/third_party/common_cells/src/deprecated/isochronous_spill_register.sv
rtl/third_party/common_cells/src/deprecated/lfsr_8bit.sv
rtl/third_party/common_cells/src/deprecated/lfsr_16bit.sv
rtl/third_party/common_cells/src/deprecated/lfsr.sv
rtl/third_party/common_cells/src/deprecated/lossy_valid_to_stream.sv
rtl/third_party/common_cells/src/deprecated/lzc.sv
rtl/third_party/common_cells/src/deprecated/max_counter.sv
rtl/third_party/common_cells/src/deprecated/mem_to_banks_detailed.sv
rtl/third_party/common_cells/src/deprecated/mem_to_banks.sv
rtl/third_party/common_cells/src/deprecated/multiaddr_decode.sv
rtl/third_party/common_cells/src/deprecated/mv_filter.sv
rtl/third_party/common_cells/src/deprecated/onehot_to_bin.sv
rtl/third_party/common_cells/src/deprecated/passthrough_stream_fifo.sv
rtl/third_party/common_cells/src/deprecated/plru_tree.sv
rtl/third_party/common_cells/src/deprecated/popcount.sv
rtl/third_party/common_cells/src/deprecated/read.sv
rtl/third_party/common_cells/src/deprecated/ring_buffer.sv
rtl/third_party/common_cells/src/deprecated/rr_arb_tree.sv
rtl/third_party/common_cells/src/deprecated/rstgen_bypass.sv
rtl/third_party/common_cells/src/deprecated/rstgen.sv
rtl/third_party/common_cells/src/deprecated/serial_deglitch.sv
rtl/third_party/common_cells/src/deprecated/shift_reg_gated.sv
rtl/third_party/common_cells/src/deprecated/shift_reg.sv
rtl/third_party/common_cells/src/deprecated/spill_register_flushable.sv
rtl/third_party/common_cells/src/deprecated/spill_register.sv
rtl/third_party/common_cells/src/deprecated/stream_arbiter_flushable.sv
rtl/third_party/common_cells/src/deprecated/stream_arbiter.sv
rtl/third_party/common_cells/src/deprecated/stream_delay.sv
rtl/third_party/common_cells/src/deprecated/stream_demux.sv
rtl/third_party/common_cells/src/deprecated/stream_fifo_optimal_wrap.sv
rtl/third_party/common_cells/src/deprecated/stream_fifo.sv
rtl/third_party/common_cells/src/deprecated/stream_filter.sv
rtl/third_party/common_cells/src/deprecated/stream_fork_dynamic.sv
rtl/third_party/common_cells/src/deprecated/stream_fork.sv
rtl/third_party/common_cells/src/deprecated/stream_intf.sv
rtl/third_party/common_cells/src/deprecated/stream_join_dynamic.sv
rtl/third_party/common_cells/src/deprecated/stream_join.sv
rtl/third_party/common_cells/src/deprecated/stream_mux.sv
rtl/third_party/common_cells/src/deprecated/stream_omega_net.sv
rtl/third_party/common_cells/src/deprecated/stream_register.sv
rtl/third_party/common_cells/src/deprecated/stream_throttle.sv
rtl/third_party/common_cells/src/deprecated/stream_to_mem.sv
rtl/third_party/common_cells/src/deprecated/stream_xbar.sv
rtl/third_party/common_cells/src/deprecated/sub_per_hash.sv
rtl/third_party/common_cells/src/deprecated/sync_wedge.sv
rtl/third_party/common_cells/src/deprecated/sync.sv
rtl/third_party/common_cells/src/deprecated/trip_counter.sv
rtl/third_party/common_cells/src/deprecated/unread.sv
rtl/third_party/common_cells/src/assert_rpt_pkg.sv
rtl/third_party/common_cells/src/cc_addr_decode_dync.sv
rtl/third_party/common_cells/src/cc_addr_decode_napot.sv
rtl/third_party/common_cells/src/cc_addr_decode.sv
rtl/third_party/common_cells/src/cc_binary_to_gray.sv
rtl/third_party/common_cells/src/cc_boxcar.sv
rtl/third_party/common_cells/src/cc_cb_filter.sv
rtl/third_party/common_cells/src/cc_cdc_2phase_clearable.sv
rtl/third_party/common_cells/src/cc_cdc_2phase.sv
rtl/third_party/common_cells/src/cc_cdc_4phase.sv
rtl/third_party/common_cells/src/cc_cdc_fifo_2phase.sv
rtl/third_party/common_cells/src/cc_cdc_fifo_gray_clearable.sv
rtl/third_party/common_cells/src/cc_cdc_fifo_gray.sv
rtl/third_party/common_cells/src/cc_cdc_reset_ctrlr.sv
rtl/third_party/common_cells/src/cc_clk_int_div_static.sv
rtl/third_party/common_cells/src/cc_clk_int_div.sv
rtl/third_party/common_cells/src/cc_clk_mux_glitch_free.sv
rtl/third_party/common_cells/src/cc_counter.sv
rtl/third_party/common_cells/src/cc_credit_counter.sv
rtl/third_party/common_cells/src/cc_delta_counter.sv
rtl/third_party/common_cells/src/cc_ecc_decode.sv
rtl/third_party/common_cells/src/cc_ecc_encode.sv
rtl/third_party/common_cells/src/cc_edge_detect.sv
rtl/third_party/common_cells/src/cc_edge_propagator_ack.sv
rtl/third_party/common_cells/src/cc_edge_propagator_rx.sv
rtl/third_party/common_cells/src/cc_edge_propagator_tx.sv
rtl/third_party/common_cells/src/cc_edge_propagator.sv
rtl/third_party/common_cells/src/cc_exp_backoff.sv
rtl/third_party/common_cells/src/cc_fall_through_register.sv
rtl/third_party/common_cells/src/cc_fifo.sv
rtl/third_party/common_cells/src/cc_gray_to_binary.sv
rtl/third_party/common_cells/src/cc_heaviside.sv
rtl/third_party/common_cells/src/cc_id_queue.sv
rtl/third_party/common_cells/src/cc_isochronous_4phase_handshake.sv
rtl/third_party/common_cells/src/cc_isochronous_spill_register.sv
rtl/third_party/common_cells/src/cc_lfsr_8bit.sv
rtl/third_party/common_cells/src/cc_lfsr_16bit.sv
rtl/third_party/common_cells/src/cc_lfsr.sv
rtl/third_party/common_cells/src/cc_lossy_valid_to_stream.sv
## PATCH for cc_lzc : removed /* verilator split_var */; lines 49,50
#rtl/third_party/common_cells/src/cc_lzc.sv
rtl/PATCH/third_party/common_cells/src/cc_lzc.sv 
rtl/third_party/common_cells/src/cc_majority_vote_filter.sv
rtl/third_party/common_cells/src/cc_max_counter.sv
rtl/third_party/common_cells/src/cc_mem_to_banks_detailed.sv
rtl/third_party/common_cells/src/cc_mem_to_banks.sv
rtl/third_party/common_cells/src/cc_multiaddr_decode.sv
rtl/third_party/common_cells/src/cc_onehot_to_bin.sv
rtl/third_party/common_cells/src/cc_onehot.sv
rtl/third_party/common_cells/src/cc_passthrough_stream_fifo.sv
rtl/third_party/common_cells/src/cc_plru_tree.sv
rtl/third_party/common_cells/src/cc_popcount.sv
rtl/third_party/common_cells/src/cc_read.sv
rtl/third_party/common_cells/src/cc_ring_buffer.sv
rtl/third_party/common_cells/src/cc_rr_arb_tree.sv
rtl/third_party/common_cells/src/cc_rstgen_bypass.sv
rtl/third_party/common_cells/src/cc_rstgen.sv
rtl/third_party/common_cells/src/cc_serial_deglitch.sv
rtl/third_party/common_cells/src/cc_shift_register_gated.sv
rtl/third_party/common_cells/src/cc_shift_register.sv
rtl/third_party/common_cells/src/cc_spill_register_flushable.sv
rtl/third_party/common_cells/src/cc_spill_register.sv
rtl/third_party/common_cells/src/cc_stream_arbiter.sv
rtl/third_party/common_cells/src/cc_stream_delay.sv
rtl/third_party/common_cells/src/cc_stream_demux.sv
rtl/third_party/common_cells/src/cc_stream_fifo_optimal_wrap.sv
rtl/third_party/common_cells/src/cc_stream_fifo.sv
rtl/third_party/common_cells/src/cc_stream_filter.sv
rtl/third_party/common_cells/src/cc_stream_fork_dynamic.sv
rtl/third_party/common_cells/src/cc_stream_fork.sv
rtl/third_party/common_cells/src/cc_stream_intf.sv
rtl/third_party/common_cells/src/cc_stream_join_dynamic.sv
rtl/third_party/common_cells/src/cc_stream_join.sv
rtl/third_party/common_cells/src/cc_stream_mux.sv
rtl/third_party/common_cells/src/cc_stream_omega_net.sv
rtl/third_party/common_cells/src/cc_stream_register.sv
rtl/third_party/common_cells/src/cc_stream_throttle.sv
rtl/third_party/common_cells/src/cc_stream_to_mem.sv
rtl/third_party/common_cells/src/cc_stream_xbar.sv
rtl/third_party/common_cells/src/cc_sub_per_hash.sv
rtl/third_party/common_cells/src/cc_sync_wedge.sv
rtl/third_party/common_cells/src/cc_trip_counter.sv
rtl/third_party/common_cells/src/cc_unread.sv

// AXI
-Irtl/third_party/axi/include/
rtl/third_party/axi/src/axi_pkg.sv
rtl/third_party/axi/src/axi_atop_filter.sv
rtl/third_party/axi/src/axi_burst_splitter_gran.sv
rtl/third_party/axi/src/axi_burst_splitter.sv
rtl/third_party/axi/src/axi_burst_unwrap.sv
rtl/third_party/axi/src/axi_bus_compare.sv
rtl/third_party/axi/src/axi_cdc_dst.sv
rtl/third_party/axi/src/axi_cdc_src.sv
rtl/third_party/axi/src/axi_cdc.sv
rtl/third_party/axi/src/axi_chan_compare.sv
rtl/third_party/axi/src/axi_cut.sv
rtl/third_party/axi/src/axi_delayer.sv
rtl/third_party/axi/src/axi_demux_id_counters.sv
rtl/third_party/axi/src/axi_demux_simple.sv
rtl/third_party/axi/src/axi_demux.sv
rtl/third_party/axi/src/axi_dumper.sv
rtl/third_party/axi/src/axi_dw_converter.sv
rtl/third_party/axi/src/axi_dw_downsizer.sv
rtl/third_party/axi/src/axi_dw_upsizer.sv
rtl/third_party/axi/src/axi_err_slv.sv
rtl/third_party/axi/src/axi_fifo_delay_dyn.sv
rtl/third_party/axi/src/axi_fifo.sv
rtl/third_party/axi/src/axi_from_mem.sv
rtl/third_party/axi/src/axi_id_prepend.sv
rtl/third_party/axi/src/axi_id_remap.sv
rtl/third_party/axi/src/axi_id_serialize.sv
rtl/third_party/axi/src/axi_interleaved_xbar.sv
rtl/third_party/axi/src/axi_intf.sv
rtl/third_party/axi/src/axi_inval_filter.sv
rtl/third_party/axi/src/axi_isolate.sv
rtl/third_party/axi/src/axi_iw_converter.sv
rtl/third_party/axi/src/axi_join.sv
rtl/third_party/axi/src/axi_lfsr.sv
rtl/third_party/axi/src/axi_lite_demux.sv
rtl/third_party/axi/src/axi_lite_dw_converter.sv
rtl/third_party/axi/src/axi_lite_from_mem.sv
rtl/third_party/axi/src/axi_lite_join.sv
rtl/third_party/axi/src/axi_lite_lfsr.sv
rtl/third_party/axi/src/axi_lite_mailbox.sv
rtl/third_party/axi/src/axi_lite_mux.sv
rtl/third_party/axi/src/axi_lite_regs.sv
rtl/third_party/axi/src/axi_lite_to_apb.sv
rtl/third_party/axi/src/axi_lite_to_axi.sv
rtl/third_party/axi/src/axi_lite_xbar.sv
rtl/third_party/axi/src/axi_modify_address.sv
rtl/third_party/axi/src/axi_multicut.sv
rtl/third_party/axi/src/axi_mux.sv
rtl/third_party/axi/src/axi_rw_join.sv
rtl/third_party/axi/src/axi_rw_split.sv
rtl/third_party/axi/src/axi_serializer.sv
rtl/third_party/axi/src/axi_sim_mem.sv
rtl/third_party/axi/src/axi_slave_compare.sv
rtl/third_party/axi/src/axi_throttle.sv
rtl/third_party/axi/src/axi_to_apb.sv
rtl/third_party/axi/src/axi_to_axi_lite.sv
rtl/third_party/axi/src/axi_to_detailed_mem.sv
rtl/third_party/axi/src/axi_to_mem_banked.sv
rtl/third_party/axi/src/axi_to_mem_interleaved.sv
rtl/third_party/axi/src/axi_to_mem_split.sv
rtl/third_party/axi/src/axi_to_mem.sv
rtl/third_party/axi/src/axi_xbar_unmuxed.sv
rtl/third_party/axi/src/axi_xbar.sv
rtl/third_party/axi/src/axi_xp.sv
rtl/third_party/axi/src/axi_zero_mem.sv

// Bootrom
rtl/cobalt_soc/cobalt_axi2mem.sv
firmware/boot/cobalt_boot.sv

// AXI-64 to APB 32 
#rtl/third_party/axi_slice/src/axi_ar_buffer.sv
#rtl/third_party/axi_slice/src/axi_aw_buffer.sv
#rtl/third_party/axi_slice/src/axi_b_buffer.sv
#rtl/third_party/axi_slice/src/axi_r_buffer.sv
#rtl/third_party/axi_slice/src/axi_single_slice.sv
#rtl/third_party/axi_slice/src/axi_slice_wrap.sv
#rtl/third_party/axi_slice/src/axi_slice.sv
#rtl/third_party/axi_slice/src/axi_w_buffer.sv
#rtl/third_party/axi2apb/src/axi2apb_64_32.sv

//APB
-Irtl/third_party/apb/include/

// APB UART 
-Irtl/third_party/apb_uart/include/

rtl/third_party/apb/src/apb_pkg.sv
rtl/third_party/apb_uart/src/apb_uart_wrap.sv
rtl/third_party/apb_uart/src/apb_uart.sv
rtl/third_party/apb_uart/src/reg_uart_wrap.sv
rtl/third_party/apb_uart/src/slib_clock_div.sv
rtl/third_party/apb_uart/src/slib_counter.sv
rtl/third_party/apb_uart/src/slib_edge_detect.sv
rtl/third_party/apb_uart/src/slib_fifo.sv
rtl/third_party/apb_uart/src/slib_input_filter.sv
rtl/third_party/apb_uart/src/slib_input_sync.sv
rtl/third_party/apb_uart/src/slib_mv_filter.sv
rtl/third_party/apb_uart/src/uart_baudgen.sv
rtl/third_party/apb_uart/src/uart_interrupt.sv
rtl/third_party/apb_uart/src/uart_receiver.sv
rtl/third_party/apb_uart/src/uart_transmitter.sv

-F rtl/third_party/cva6/core/Flist.cva6

#${CVA6_REPO_DIR}/corev_apu/tb/axi_intf.sv
rtl/cpu_subsys/cpu_subsys_pkg.sv
rtl/cpu_subsys/cobalt_axi_pkg.sv
rtl/cobalt_soc/cobalt_pkg.sv
rtl/cpu_subsys/cpu_subsys.sv
rtl/cobalt_soc/cobalt_soc.sv