// -----------------------------------------------------------------------------
// Auto-generated Cobalt Boot ROM
//
// DO NOT EDIT MANUALLY.
// Generated by gen_rom.py
// -----------------------------------------------------------------------------

module cobalt_boot #(
    parameter int unsigned ROM_WORDS = 2
) (
    input  logic                     clk_i,
    input  logic                     req_i,
    input  logic [63:0]              addr_i,
    output logic [63:0]              rdata_o
);

    localparam int unsigned ADDR_WIDTH = 1;

    logic [63:0] mem [0:ROM_WORDS-1];
    logic [ADDR_WIDTH-1:0] addr_q;

    // -------------------------------------------------------------------------
    // ROM contents
    // -------------------------------------------------------------------------
    initial begin
        mem[0] = 64'h257302FE0010029B;
        mem[1] = 64'h0000A0018282F140;
    end

    // -------------------------------------------------------------------------
    // Synchronous read address
    //
    // The ROM is 64-bit word addressed, therefore address bits [..:3]
    // select the ROM word.
    // -------------------------------------------------------------------------
    always_ff @(posedge clk_i) begin
        if (req_i) begin
            addr_q <= addr_i[ADDR_WIDTH+2:3];
        end
    end

    // -------------------------------------------------------------------------
    // ROM data output
    // -------------------------------------------------------------------------
    always_comb begin
        if (addr_q < ROM_WORDS)
            rdata_o = mem[addr_q];
        else
            rdata_o = '0;
    end

endmodule
