#!/usr/bin/env python3

import argparse
import os
import sys


WORD_BYTES = 8
WORD_BITS = 64


def read_binary(filename):
    """Read binary image and pad it to a 64-bit word boundary."""

    try:
        with open(filename, "rb") as f:
            data = bytearray(f.read())
    except OSError as e:
        print(f"ERROR: cannot read '{filename}': {e}", file=sys.stderr)
        sys.exit(1)

    original_size = len(data)

    # Pad to 64-bit word boundary.
    padding = (-len(data)) % WORD_BYTES

    if padding:
        data.extend([0] * padding)

    print(f"Input file      : {filename}")
    print(f"Input size      : {original_size} bytes")
    print(f"Padding         : {padding} bytes")
    print(f"ROM size        : {len(data)} bytes")
    print(f"ROM words       : {len(data) // WORD_BYTES}")

    return data


def bytes_to_words(data):
    """Convert byte array into 64-bit little-endian words."""

    words = []

    for offset in range(0, len(data), WORD_BYTES):
        word_bytes = data[offset:offset + WORD_BYTES]

        # Binary image is little-endian.
        #
        # Example:
        #   bytes = 9b 02 10 00 fe 02 73 25
        #
        # becomes:
        #   64'h257302FE0010029B
        #
        word = int.from_bytes(word_bytes, byteorder="little")

        words.append(word)

    return words


def generate_sv(words, module_name, output_filename):
    """Generate SystemVerilog ROM."""

    rom_words = len(words)
    addr_width = max(1, (rom_words - 1).bit_length())

    with open(output_filename, "w") as f:

        f.write("// -----------------------------------------------------------------------------\n")
        f.write("// Auto-generated Cobalt Boot ROM\n")
        f.write("//\n")
        f.write("// DO NOT EDIT MANUALLY.\n")
        f.write("// Generated by gen_rom.py\n")
        f.write("// -----------------------------------------------------------------------------\n\n")

        f.write("module {} #(\n".format(module_name))
        f.write("    parameter int unsigned ROM_WORDS = {}\n".format(rom_words))
        f.write(") (\n")
        f.write("    input  logic                     clk_i,\n")
        f.write("    input  logic                     req_i,\n")
        f.write("    input  logic [63:0]              addr_i,\n")
        f.write("    output logic [63:0]              rdata_o\n")
        f.write(");\n\n")

        f.write("    localparam int unsigned ADDR_WIDTH = {};\n\n".format(addr_width))

        f.write("    logic [63:0] mem [0:ROM_WORDS-1];\n")
        f.write("    logic [ADDR_WIDTH-1:0] addr_q;\n\n")

        # ROM contents
        f.write("    // -------------------------------------------------------------------------\n")
        f.write("    // ROM contents\n")
        f.write("    // -------------------------------------------------------------------------\n")
        f.write("    initial begin\n")

        for index, word in enumerate(words):
            f.write(
                "        mem[{}] = 64'h{:016X};\n".format(
                    index,
                    word
                )
            )

        f.write("    end\n\n")

        # Address register
        f.write("    // -------------------------------------------------------------------------\n")
        f.write("    // Synchronous read address\n")
        f.write("    //\n")
        f.write("    // The ROM is 64-bit word addressed, therefore address bits [..:3]\n")
        f.write("    // select the ROM word.\n")
        f.write("    // -------------------------------------------------------------------------\n")

        f.write("    always_ff @(posedge clk_i) begin\n")
        f.write("        if (req_i) begin\n")
        f.write("            addr_q <= addr_i[ADDR_WIDTH+2:3];\n")
        f.write("        end\n")
        f.write("    end\n\n")

        # Data output
        f.write("    // -------------------------------------------------------------------------\n")
        f.write("    // ROM data output\n")
        f.write("    // -------------------------------------------------------------------------\n")

        f.write("    always_comb begin\n")
        f.write("        if (addr_q < ROM_WORDS)\n")
        f.write("            rdata_o = mem[addr_q];\n")
        f.write("        else\n")
        f.write("            rdata_o = '0;\n")
        f.write("    end\n\n")

        f.write("endmodule\n")

    print(f"Generated SV    : {output_filename}")


def main():

    parser = argparse.ArgumentParser(
        description="Generate a 64-bit SystemVerilog ROM from a binary image."
    )

    parser.add_argument(
        "input",
        help="Input binary image (.img)"
    )

    parser.add_argument(
        "-o",
        "--output",
        help="Output SystemVerilog file"
    )

    parser.add_argument(
        "-m",
        "--module",
        help="SystemVerilog module name"
    )

    args = parser.parse_args()

    input_file = args.input

    if not os.path.isfile(input_file):
        print(
            f"ERROR: input file '{input_file}' does not exist.",
            file=sys.stderr
        )
        sys.exit(1)

    # Default output name.
    if args.output:
        output_file = args.output
    else:
        output_file = os.path.splitext(input_file)[0] + ".sv"

    # Default module name.
    if args.module:
        module_name = args.module
    else:
        module_name = os.path.splitext(
            os.path.basename(input_file)
        )[0]

    # SystemVerilog identifiers cannot contain '-'.
    module_name = module_name.replace("-", "_")

    data = read_binary(input_file)
    words = bytes_to_words(data)

    generate_sv(
        words,
        module_name,
        output_file
    )


if __name__ == "__main__":
    main()